
server:
  port: 8761

spring:
  application:
    name: ms-eureka-server
  # Desabilita o acesso ao banco de dados para o Eureka (que não precisa de BD)
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  client:
    # CRÍTICO: Indica que este é o servidor e ele não deve se registrar
    register-with-eureka: false
    fetch-registry: false
  server:
    # Aumenta o tempo de espera para serviços se registrarem
    eviction-interval-timer-in-ms: 10000